FROM postgres:17.4

# COPY ./init.sql /docker-entrypoint-initdb.d/
# COPY create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/

# RUN chmod 0666 /docker-entrypoint-initdb.d/setup-master.sh